### ISSUE TITLE
Left margin too small on Xorg

### ISSUE THREAD

**Issue by josineto** [johnfactotum/gedit-restore-zen#1]
Hi, thank you for this plugin! In my notebook (1366x768 pixels), the left margin added in fullscreen is too small, making almost no difference at all. Analysing following screenshot in GIMP, I see left margin with ~60px only:

![Screenshot](https://user-images.githubusercontent.com/35090091/78380688-a157d700-75aa-11ea-853b-599803f5ed9d.png)

**Comment by josineto** [comment]
A little comment: even when I activate text-wrapping, it only wraps at window border. Is there a way to wrap text at a fixed number of characters (80 characters, for instance)?

**Comment by johnfactotum** [comment]
I can't reproduce the problem. I don't have a smaller screen, but I've tried enabling hdpi, which makes the effective resolution lower than 1366x768, and it seems to work as expected. Maybe you can try un-fullscreen and re-fullscreen again? If that doesn't work then maybe try adding `print(window_width, text_width, gutter_width)` at around line 26 and see which of the widths are being calculated wrong.

As for wraping at the right margin, it seems that gtksourceview doesn't have this feature. But one might be able to achieve the same effect by adding a right margin or padding. I think an easier way might be to change the alignment of the view widget, then reduce its width.

**Comment by johnfactotum** [comment]
Okay, I see the problem. It works correctly on Wayland, but not on Xorg.

**Comment by johnfactotum** [comment]
For wrapping at a fixed number of characters, try this patch:
```diff
diff --git a/restore_zen.py b/restore_zen.py
index bb1bdf0..cbdca8b 100644
--- a/restore_zen.py
+++ b/restore_zen.py
@@ -26,9 +26,12 @@ class RestoreZenPlugin(GObject.Object, Gedit.WindowActivatable):
 
             margin = (window_width - text_width - gutter_width) / 2
             view.set_margin_left(margin)
+            view.set_margin_right(margin)
 
     def uncenter_views(self):
-        for view in self.get_views(): view.set_margin_left(0)
+        for view in self.get_views():
+            view.set_margin_left(0)
+            view.set_margin_right(0)
 
     def on_window_state_event(self, _, event):
         state = event.get_window().get_state()
```

**Comment by josineto** [comment]
Thank you, left margin sized correctly now! Later I'll try your patch and post here.

**Comment by josineto** [comment]
Your patch works perfectly! Thank you, and sorry for not saying my system uses Xorg from the start.

It would be wonderful to make such patch through plugin preferences (there's a button `Preferences` in Gedit's list of plugins). I don't know how complex this is, but it's a suggestion, anyway.

Here a screenshot with your patch:

![Captura de tela de 2020-04-03 22-12-15](https://user-images.githubusercontent.com/35090091/78415465-4220b380-75f8-11ea-9b96-4e9cd1ac4337.png)

Thank you again, now I can use Gedit to confortably write not only code, but also other types of text.

**Comment by johnfactotum** [comment]
Preferences added in 4c8fdbc!
